name: "alpha-Fe"
a: 2.866
b: 2.866
c: 2.866
alpha: 90
beta: 90
gamma: 90
space_group: null
atoms: [
  ["Fe", 0.0, 0.0, 0.0, 1.0, 0.4],
  ["Fe", 0.5, 0.5, 0.5, 1.0, 0.4]
]
wavelength: 0.71
twotheta_range: [20, 100, 0.02]
thetam_deg: 0.
U: 0.01
V: -0.005
W: 0.005
scale: 1.0
profile: "stick"
eta: 0.5
intensity_units: "arbitrary"
normalize_intensity: true
intensity_max_value: 100
intensity_min: 0.0000
multiplicity_mode: symmetry
multiplicity_metric_rtol: 1.0e-7
multiplicity_metric_atol: 1.0e-12