name: "Alpha-Quartz"
lattice_family: hexagonal
bravais_centering: none
space_group: null

a: 4.913
c: 5.405

atoms: [
  ["Si", 0.4697, 0.0, 0.0, 1.0, 0.5],
  ["O", 0.4135, 0.2669, 0.1191, 1.0, 0.5],
]

wavelength: 1.5418
twotheta_range: [5, 150, 0.02]
profile: bar
thetam_deg: 0.0
