name: "alpha-Fe"
a: 2.866
b: 2.866
c: 2.866
alpha: 90
beta: 90
gamma: 90
space_group: 529
atoms: [
  ["Fe", 0.0, 0.0, 0.0, 1.0, 0.4]
]
wavelength: 1.5418
twotheta_range: [20, 100, 0.02]
U: 0.01
V: -0.005
W: 0.005
scale: 1.0
profile: "stick"
eta: 0.5
intensity_units: "arbitrary"
normalize_intensity: true
intensity_max_value: 100