name: "Alpha-Quartz"
a: 4.913
b: 4.913
c: 5.405
alpha: 90
beta: 90
gamma: 120
space_group: 454
atoms: [
  ["Si", 0.4697, 0.0, 0.0, 1.0, 0.5],
  ["O", 0.4135, 0.2669, 0.1191, 1.0, 0.5]
]
wavelength: 1.5418
twotheta_range: [20, 100, 0.02]
thetam_deg: 0.
U: 0.01
V: -0.005
W: 0.005
scale: 1.0
profile: "stick"
eta: 0.5
intensity_units: "arbitrary"
normalize_intensity: true
intensity_max_value: 100
