name: "Bismuth (Bi)"
lattice_family: hexagonal
bravais_centering: none
space_group: null

a: 4.546
c: 11.862

atoms: [
  ["Bi", 0.0, 0.0, 0.233, 1.0, 0.5],
]

wavelength: 1.5418
twotheta_range: [5, 150, 0.02]
profile: bar
thetam_deg: 0.0
