# Гексагональная система: задайте a и c (b=a, α=β=90°, γ=120° подставятся).
name: "Mg"
lattice_family: hexagonal
bravais_centering: none
space_group: null

a: 3.209
c: 5.211

atoms: [
  ["Mg", 0.0, 0.0, 0.0, 1.0, 0.8],
  ["Mg", 0.3333, 0.6667, 0.5, 1.0, 0.8],
]

wavelength: 1.5418
twotheta_range: [5, 150, 0.02]
profile: stick
thetam_deg: 0.0
