name: "NaCl"
a: 5.64
b: 5.64
c: 5.64
alpha: 90
beta: 90
gamma: 90
space_group: 523
atoms: [
  ["Na", 0, 0, 0, 1.0, 1.6],
  ["Cl", 0.5, 0.5, 0.5, 1.0, 1.35]
]
wavelength: 1.5418
twotheta_range: [20, 100, 0.02]
thetam_deg: 0.
U: 0.01
V: -0.005
W: 0.005
scale: 1.0
profile: "stick"
eta: 0.5
intensity_units: "arbitrary"
normalize_intensity: true
intensity_max_value: 100
intensity_min: 0.0001
multiplicity_mode: metric
multiplicity_metric_rtol: 1.0e-7
multiplicity_metric_atol: 1.0e-12